version: '3.8'
services:
  appseed-app:
    container_name: ocrapi_app
    restart: always
    # image: "ocr-service_appseed-app:latest"
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge