version: '3.8'
services:
  web:
    container_name: ocr_app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn --config gunicorn-cfg.py core.wsgi
    expose:
      - 8000
    # volumes:
    #   - static_volume:/home/app/web/staticfiles
    restart: always
    env_file: .env
    depends_on:
      - db
  db:
    container_name: ocr_postgres
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DATABASE: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASS}"
  nginx:
    container_name: ocr_nginx
    build: ./nginx
    restart: always
    # image: "nginx:latest"
    ports:
      - "8000:80"
    # volumes:
    #   - ./nginx:/etc/nginx/conf.d
    #   - static_volume:/home/app/web/staticfiles
    depends_on: 
      - web

volumes:
  postgres_data:
  static_volume:

 