# Generated by Django 3.2.6 on 2022-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='biz_process',
            field=models.CharField(max_length=200, null=True, verbose_name='Business Process'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='doc_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Document Name'),
        ),
    ]
